apiVersion: apps/v1
kind: Deployment
metadata:
  name: highlight-erp-php-deployment
  labels:
    app: highlight-erp-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: highlight-erp-php
  template:
    metadata:
      labels:
        app: highlight-erp-php
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: php-fpm
          image: registry.zennex.ru/highlight-erp/php:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: php-fpm
          envFrom:
            - secretRef:
                name: highlight-erp-env
          volumeMounts:
            - name: storage
              mountPath: /var/www/html/storage/app
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: highlight-erp-storage-pvc
