apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: highlight-erp-storage-pvc
  labels:
    app: highlight-erp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
